### ISSUE TITLE
Veryable: Phase 1

### ISSUE THREAD

**Issue by mlahargou** [iFixit/Veryable#23]
# Description:

Let's figure out the sub-tasks necessary to get Phase 1 of Veryable done. 

- [ ]  Convert parsing logic from run time analysis to historical analysis #8 
- [ ]  Create and run migrations for new tables - reference table in #21 
- [ ]  Run backfilling script to populate previously `MERGED` and `CLOSED` pulls
- [ ]  Create Docker container to run on Cominor like Pulldasher
    - [ ]  Need to create prod env configurations

### Preview of Phase 2:

- Team:
    - Cycles through discussing and trying to move metrics
    - Evaluates usefulness of metrics
    - Identifies new metrics or changes to existing metrics
    - Identifies bugs in current implementation

**Comment by mlahargou** [comment]
This isn't high on our priority list at the moment.
